name: Test Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard
          sudo cp scripts/openg2p-e2e.conf /etc/wireguard/
          sudo systemctl start wg-quick@openg2p-e2e.service

      - name: Chrome setup
        uses: browser-actions/setup-chrome@v1

      - run: chrome --version

      - name: Chromedriver setup
        uses: nanasess/setup-chromedriver@v2

      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run Sanity tests
        run: mvn clean test

      - name: List Allure results
        run: ls -laR target/allure-results

      - name: Install Allure CLI
        run: |
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure_2.25.0-1_all.deb
          sudo dpkg -i allure_2.25.0-1_all.deb

      - name: Generate Allure Report
        run: |
          allure generate target/allure-results --clean -o allure-report

      - name: List generated Allure report
        run: ls -laR allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.TOKEN }}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.sha }}
          target_url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Slack Notification on failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: '{"text": "*Workflow failed.*\nActor: ${{ github.actor }}\nCommit ID: ${{ github.sha }}\nFailed Step: ${{ github.event_name }}"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK }}

      - name: Slack Notification on success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: '{"text": "*Workflow ran successfully.*\nActor: ${{ github.actor }}\nCommit ID: ${{ github.sha }}"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
